// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRow: typeof import('element-plus/es')['ElRow']
    MyComp1: typeof import('./src/components/MyComp1.vue')['default']
    MyComp2: typeof import('./src/components/MyComp2.vue')['default']
    MyComp3: typeof import('./src/components/MyComp3.vue')['default']
  }
}

export { }
